const Cdata = [
    {
        Club:"COSC",
        PresidentName:"Dhruv Saxena",
        PresidentContact:"89783 83634",
        VicePresidentName:"Gopal Matcha",
        VicePresidentContact:"98480 39729",
        ClubMember1:"Karthikeya",
        ClubMember2:"Safa Mahreen",
        ClubMember3:"Yetish Manne",
        ClubMember4:"Ashmit",
        ClubMember5:"Harshith",
        ClubMember6:"Sai Akshitha",
    },
    {
        Club:"ROBOVANZA",
        PresidentName:"Nikhil",
        PresidentContact:"8106274309",
        VicePresidentName:"Ayushi",
        VicePresidentContact:"6303601280",
        ClubMember1:"Jahnavi",
        ClubMember2:"Geetika",
        ClubMember3:"Sujith",
        ClubMember4:"Tulasi",
        ClubMember5:"Muzzamil",
        ClubMember6:"Charan",
    },
    {
        Club:"SPANDANA",
        PresidentName:"Pashya Sathwik",
        PresidentContact:"9000300086",
        VicePresidentName:"Anam Fathima",
        VicePresidentContact:"9834879834",
        AboutClub:"    about club   ",
        ClubMember1:"Akhil",
        ClubMember2:"Dhekshagna",
        ClubMember3:"Devesh Newar",
        ClubMember4:"Tejas",
        ClubMember5:"Rohith",
        ClubMember6:"Rajesh",
    },
    {
        Club:"Makers Of India",
        PresidentName:"Prithvi Sandeep",
        PresidentContact:"7330789283",
        VicePresidentName:"Sai Anirudh",
        VicePresidentContact:"8897011526",
        AboutClub:"    about club   ",
        ClubMember1:"Kathyayini",
        ClubMember2:"Vishnu Chary",
        ClubMember3:"Hasan Pasha",
        ClubMember4:"Sri Meghana",
        ClubMember5:"Mohammad Sonu",
        ClubMember6:"Supriya",
    }
]

export default Cdata;