const Data = [
    {
        Name:"Akshitha Jadav Lakavath",
        Username:"ugs21071_aids.akshitha@cbit.org.in",
        Password:"cbit@123",
        RollNumber:"160121748045",
        Admission:"2114261",
        ClassHeld:"290",
        ClassAttended:"258",
        OverAllAttendance:"89%",
        Java:{
            ClassHeld:"30",
            ClassAttended:"28",
            OverAllAttendance:"93%"
        },
        JavaLab:{
            ClassHeld:"26",
            ClassAttended:"18",
            OverAllAttendance:"82%"
        },
        AIML:{
            ClassHeld:"7",
            ClassAttended:"7",
            OverAllAttendance:"100%"
        },
        ICFT:{
            ClassHeld:"24",
            ClassAttended:"20",
            OverAllAttendance:"83%"
        },
        DCCST:{
            ClassHeld:"36",
            ClassAttended:"33",
            OverAllAttendance:"92%"
        },
        DLCA:{
            ClassHeld:"34",
            ClassAttended:"30",
            OverAllAttendance:"88%"
        },
        DBMS:{
            ClassHeld:"39",
            ClassAttended:"34",
            OverAllAttendance:"87%"
        },
        DBMSLab:{
            ClassHeld:"24",
            ClassAttended:"20",
            OverAllAttendance:"83%"
        },
        MiniProject:{
            ClassHeld:"20",
            ClassAttended:"18",
            OverAllAttendance:"90%"
        },
        Maths:{
            ClassHeld:"31",
            ClassAttended:"31",
            OverAllAttendance:"100%"
        },
        Mentoring:{
            ClassHeld:"16",
            ClassAttended:"12",
            OverAllAttendance:"75%"
        }
        
    },
    {
        Name:"Vaishak Reddy",
        Username:"",
        Password:"",
        RollNumber:"160121771102",
        Admission:"2021",
        ClassHeld:"",
        ClassAttended:"",
        OverAllAttendance:"78",
        Java:{
            ClassHeld:"30",
            ClassAttended:"",
            OverAllAttendance:"%"
        },
        JavaLab:{
            ClassHeld:"26",
            ClassAttended:"",
            OverAllAttendance:"%"
        },
        AIML:{
            ClassHeld:"7",
            ClassAttended:"",
            OverAllAttendance:"%"
        },
        ICFT:{
            ClassHeld:"20",
            ClassAttended:"",
            OverAllAttendance:"%"
        },
        DCCST:{
            ClassHeld:"33",
            ClassAttended:"",
            OverAllAttendance:"%"
        },
        DLCA:{
            ClassHeld:"34",
            ClassAttended:"29",
            OverAllAttendance:"%"
        },
        DBMS:{
            ClassHeld:"36",
            ClassAttended:"33",
            OverAllAttendance:"%"
        },
        DBMSLab:{
            ClassHeld:"20",
            ClassAttended:"",
            OverAllAttendance:"%"
        },
        MiniProject:{
            ClassHeld:"24",
            ClassAttended:"",
            OverAllAttendance:"%"
        },
        Maths:{
            ClassHeld:"31",
            ClassAttended:"",
            OverAllAttendance:"%"
        },
        Mentoring:{
            ClassHeld:"16",
            ClassAttended:"",
            OverAllAttendance:"%"
        }
    },
    {
        Name:"Moses Padirolu",
        Username:"ugs21116_aids.moses@cbit.org.in",
        Password:"cbit@123",
        RollNumber:"160121771116",
        Admission:"2114260",
        ClassHeld:"284",
        ClassAttended:"256",
        OverAllAttendance:"90%",
        Java:{
            ClassHeld:"30",
            ClassAttended:"25",
            OverAllAttendance:"83%"
        },
        JavaLab:{
            ClassHeld:"26",
            ClassAttended:"26",
            OverAllAttendance:"100%"
        },
        AIML:{
            ClassHeld:"7",
            ClassAttended:"7",
            OverAllAttendance:"100%"
        },
        ICFT:{
            ClassHeld:"20",
            ClassAttended:"17",
            OverAllAttendance:"85%"
        },
        DCCST:{
            ClassHeld:"33",
            ClassAttended:"32",
            OverAllAttendance:"97%"
        },
        DLCA:{
            ClassHeld:"34",
            ClassAttended:"29",
            OverAllAttendance:"85%"
        },
        DBMS:{
            ClassHeld:"36",
            ClassAttended:"33",
            OverAllAttendance:"92%"
        },
        DBMSLab:{
            ClassHeld:"20",
            ClassAttended:"15",
            OverAllAttendance:"75%"
        },
        MiniProject:{
            ClassHeld:"24",
            ClassAttended:"22",
            OverAllAttendance:"92%"
        },
        Maths:{
            ClassHeld:"31",
            ClassAttended:"31",
            OverAllAttendance:"100%"
        },
        Mentoring:{
            ClassHeld:"16",
            ClassAttended:"12",
            OverAllAttendance:"75%"
        }
        
    },
    {
        Name:"Bingi Pranav",
        RollNumber:"160121771098",
        Admission:"2021",
        ClassHeld:"",
        ClassAttended:"",
        OverAllAttendance:"60",
        Java:{
            ClassHeld:"30",
            ClassAttended:"19",
            OverAllAttendance:"63%"
        },
        JavaLab:{
            ClassHeld:"26",
            ClassAttended:"20",
            OverAllAttendance:"77%"
        },
        AIML:{
            ClassHeld:"14",
            ClassAttended:"8",
            OverAllAttendance:"57%"
        },
        ICFT:{
            ClassHeld:"20",
            ClassAttended:"13",
            OverAllAttendance:"65%"
        },
        DCCST:{
            ClassHeld:"33",
            ClassAttended:"20",
            OverAllAttendance:"61%"
        },
        DLCA:{
            ClassHeld:"34",
            ClassAttended:"10",
            OverAllAttendance:"29%"
        },
        DBMS:{
            ClassHeld:"36",
            ClassAttended:"22",
            OverAllAttendance:"61%"
        },
        DBMSLab:{
            ClassHeld:"20",
            ClassAttended:"12",
            OverAllAttendance:"60%"
        },
        MiniProject:{
            ClassHeld:"24",
            ClassAttended:"12",
            OverAllAttendance:"50%"
        },
        Maths:{
            ClassHeld:"31",
            ClassAttended:"29",
            OverAllAttendance:"94%"
        },
        Mentoring:{
            ClassHeld:"16",
            ClassAttended:"6",
            OverAllAttendance:"38%"
        },
    },
    {
        Name:"Sree Harsha",
        RollNumber:"160121771100",
        Admission:"2021",
        ClassHeld:"",
        ClassAttended:"",
        OverAllAttendance:"85",
        Java:{
            ClassHeld:"30",
            ClassAttended:"25",
            OverAllAttendance:"83%"
        },
        JavaLab:{
            ClassHeld:"26",
            ClassAttended:"24",
            OverAllAttendance:"92%"
        },
        AIML:{
            ClassHeld:"14",
            ClassAttended:"14",
            OverAllAttendance:"100%"
        },
        ICFP:{
            ClassHeld:"20",
            ClassAttended:"13",
            OverAllAttendance:"65%"
        },
        DCCST:{
            ClassHeld:"33",
            ClassAttended:"27",
            OverAllAttendance:"82%"
        },
        DLCA:{
            ClassHeld:"34",
            ClassAttended:"25",
            OverAllAttendance:"74%"
        },
        DBMS:{
            ClassHeld:"36",
            ClassAttended:"33",
            OverAllAttendance:"92%"
        },
        DBMSLab:{
            ClassHeld:"20",
            ClassAttended:"20",
            OverAllAttendance:"100%"
        },
        MiniProject:{
            ClassHeld:"24",
            ClassAttended:"20",
            OverAllAttendance:"83%"
        },
        Maths:{
            ClassHeld:"31",
            ClassAttended:"29",
            OverAllAttendance:"94%"
        },
        Mentoring:{
            ClassHeld:"16",
            ClassAttended:"10",
            OverAllAttendance:"63%"
        },
    },
    {
        Name:"Sanjeev Varma",
        RollNumber:"160121771105",
        Admission:"2021",
        ClassHeld:"",
        ClassAttended:"",
        OverAllAttendance:"",
        Java:{
            ClassHeld:"30",
            ClassAttended:"27",
            OverAllAttendance:"90%"
        },
        JavaLab:{
            ClassHeld:"26",
            ClassAttended:"18",
            OverAllAttendance:"69%"
        },
        AIML:{
            ClassHeld:"14",
            ClassAttended:"12",
            OverAllAttendance:"86%"
        },
        ICFT:{
            ClassHeld:"20",
            ClassAttended:"16",
            OverAllAttendance:"80%"
        },
        DCCST:{
            ClassHeld:"33",
            ClassAttended:"25",
            OverAllAttendance:"76%"
        },
        DLCA:{
            ClassHeld:"34",
            ClassAttended:"28",
            OverAllAttendance:"82%"
        },
        DBMS:{
            ClassHeld:"36",
            ClassAttended:"32",
            OverAllAttendance:"89%"
        },
        DBMSLab:{
            ClassHeld:"20",
            ClassAttended:"18",
            OverAllAttendance:"90%"
        },
        MiniProject:{
            ClassHeld:"24",
            ClassAttended:"18",
            OverAllAttendance:"75%"
        },
        Maths:{
            ClassHeld:"31",
            ClassAttended:"31",
            OverAllAttendance:"100%"
        },
        Mentoring:{
            ClassHeld:"16",
            ClassAttended:"10",
            OverAllAttendance:"63%"
        },
    },
    {
        Name:"Rohith",
        RollNumber:"160121771111",
        Admission:"2021",
        ClassHeld:"",
        ClassAttended:"",
        OverAllAttendance:"",
        Java:{
            ClassHeld:"30",
            ClassAttended:"26",
            OverAllAttendance:"87%"
        },
        JavaLab:{
            ClassHeld:"26",
            ClassAttended:"24",
            OverAllAttendance:"92%"
        },
        AIML:{
            ClassHeld:"14",
            ClassAttended:"14",
            OverAllAttendance:"100%"
        },
        ICFT:{
            ClassHeld:"20",
            ClassAttended:"19",
            OverAllAttendance:"95%"
        },
        DCCST:{
            ClassHeld:"33",
            ClassAttended:"30",
            OverAllAttendance:"91%"
        },
        DLCA:{
            ClassHeld:"34",
            ClassAttended:"28",
            OverAllAttendance:"82%"
        },
        DBMS:{
            ClassHeld:"36",
            ClassAttended:"33",
            OverAllAttendance:"92%"
        },
        DBMSLab:{
            ClassHeld:"20",
            ClassAttended:"15",
            OverAllAttendance:"75%"
        },
        MiniProject:{
            ClassHeld:"24",
            ClassAttended:"18",
            OverAllAttendance:"75%"
        },
        Maths:{
            ClassHeld:"31",
            ClassAttended:"31",
            OverAllAttendance:"100%"
        },
        Mentoring:{
            ClassHeld:"16",
            ClassAttended:"14",
            OverAllAttendance:"88%"
        },
    },
    {
        Name:"Abhideep",
        RollNumber:"160121771108",
        Admission:"2021",
        ClassHeld:"",
        ClassAttended:"",
        OverAllAttendance:"",
        Java:{
            ClassHeld:"30",
            ClassAttended:"24",
            OverAllAttendance:"80%"
        },
        JavaLab:{
            ClassHeld:"26",
            ClassAttended:"24",
            OverAllAttendance:"92%"
        },
        AIML:{
            ClassHeld:"14",
            ClassAttended:"10",
            OverAllAttendance:"71%"
        },
        ICFT:{
            ClassHeld:"20",
            ClassAttended:"18",
            OverAllAttendance:"90%"
        },
        DCCST:{
            ClassHeld:"33",
            ClassAttended:"28",
            OverAllAttendance:"85%"
        },
        DLCA:{
            ClassHeld:"34",
            ClassAttended:"27",
            OverAllAttendance:"79%"
        },
        DBMS:{
            ClassHeld:"36",
            ClassAttended:"32",
            OverAllAttendance:"89%"
        },
        DBMSLab:{
            ClassHeld:"20",
            ClassAttended:"17",
            OverAllAttendance:"85%"
        },
        MiniProject:{
            ClassHeld:"24",
            ClassAttended:"18",
            OverAllAttendance:"75%"
        },
        Maths:{
            ClassHeld:"31",
            ClassAttended:"29",
            OverAllAttendance:"94%"
        },
        Mentoring:{
            ClassHeld:"16",
            ClassAttended:"12",
            OverAllAttendance:"75%"
        },
    }
]

export default Data;